# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
    :internetRouter => {
        :box_name => "centos/7",
        :fw => {},
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
            {ip: '192.168.255.1',   adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "inet-net"},
        ]
    },
    :centralRouter => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.255.2',   adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "inet-net"},
            {ip: '192.168.0.1',     adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
            {ip: '192.168.0.33',    adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
            {ip: '192.168.0.65',    adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
        ]
    },

    :webServer => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.0.2',     adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
        ]
    },

    :appRouter => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.0.34',    adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
            {ip: '192.168.2.1',     adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "reserved-1-net"},
            {ip: '192.168.2.65',    adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "reserved-2-net"},
            {ip: '192.168.2.129',   adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "reserved-3-net"},
            {ip: '192.168.2.193',   adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "app-net"},
        ]
    },

    :appServer => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.2.194',   adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "app-net"},
        ]
    },

    :dbRouter => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.0.35',    adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
            {ip: '192.168.1.1',     adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "hw-reserved-1-net"},
            {ip: '192.168.1.129',   adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "hw-reserved-2-net"},
            {ip: '192.168.1.193',   adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "db-net"},
        ]
    },

    :dbServer => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.1.194',   adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "db-net"},
        ]
    },
    :dbBackupServer => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.1.195',   adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "db-net"},
        ]
    },

    :monitoringServer => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.0.66',   adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
        ]
    },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.gatling.rsync_on_startup = false

        config.vm.define boxname do |box|


            box.vm.provision "shell", run: "always", inline: <<-SHELL

                systemctl stop NetworkManager
                systemctl disable NetworkManager

                systemctl enable network.service
                systemctl start network.service

                # yum install -y traceroute
                # yum install -y nano
            SHELL

            config.vm.provider "virtualbox" do |v|
                v.memory = 256
                v.cpus = 1
            end


            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
                box.vm.network "private_network", ipconf
                case boxname.to_s
                when "internetRouter"
                   box.vm.network :forwarded_port, guest: 80, host: 8080
                   box.vm.network :forwarded_port, guest: 443, host: 8443
                   box.vm.network :forwarded_port, guest: 443, host: 443

                   box.vm.network :forwarded_port, guest: 8000, host: 8000
                end
            end

            if boxconfig.key?(:public)
                box.vm.network "public_network", boxconfig[:public]
            end

            #if boxconfig.key?(:fw)
            #    box.vm.network "forwarded_port", guest: 443, host: 443, host_ip: '127.0.0.1', guest_ip: '192.168.0.2';
            #end

            box.vm.provision "shell", inline: <<-SHELL
                mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL

        end
        end

    end
