networks_hosts:
  internetRouter:
    default_gateway:
      interface: eth0
      gw: ''
    routes:
      - { interface: eth1, nw: 192.168.0.0/16, via: 192.168.255.2 }
    forwarding: 1
  centralRouter:
    default_gateway:
      interface: eth1
      gw: 192.168.255.1
    routes:
      - { interface: eth3, nw: 192.168.2.0/24, via: 192.168.0.34 }
      - { interface: eth3, nw: 192.168.1.0/24, via: 192.168.0.35 }
    forwarding: 1
  webServer:
    default_gateway:
      interface: eth1
      gw: 192.168.0.1
    routes: []
  appRouter:
    default_gateway:
      interface: eth1
      gw: 192.168.0.33
    routes: []
    forwarding: 1
  appServer:
    default_gateway:
      interface: eth1
      gw: 192.168.2.193
    routes: []
  dbRouter:
    default_gateway:
      interface: eth1
      gw: 192.168.0.33
    routes: []
    forwarding: 1
  dbServer:
    default_gateway:
      interface: eth1
      gw: 192.168.1.193
    routes: []
  dbBackupServer:
    default_gateway:
      interface: eth1
      gw: 192.168.1.193
    routes: []
  monitoringServer:
    default_gateway:
      interface: eth1
      gw: 192.168.0.65
    routes: []
